apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: hadoop-master
  name: hadoop-master
  namespace: hadoop-master
spec:
  selector:
    app: hadoop-master
  template:
    metadata:
      labels:
        app: hadoop-master
    spec:
      containers:
      - image: kiwenlau/hadoop:1.0
        imagePullPolicy: Always
        name: hadoop-master
        securityContext:
          privileged: true
        ports:
        - containerPort: 50070
        - containerPort: 8088
