apiVersion: v1
kind: Service
metadata:
  name: hadoop-master
  labels:
    app: hadoop-master
spec:
  ports:
    - port: 50070
      name: hadoop-masternode
    - port: 8088
      name: hadoop-resourcemanager
    - port: 9000
      name: hadoop-hdfs
  selector:
    app: hadoop-master
