#### Hadoop Master  replication controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: hadoop-master
  name: hadoop-master
  namespace: default
spec:
  selector:
    app: hadoop-master
  template:
    metadata:
      labels:
        app: hadoop-master
    spec:
      containers:
      - image: tantru/hadoop-master:1.0
        imagePullPolicy: Always
        name: hadoop-master
        ports:
        - containerPort: 50070
          protocol: TCP
        - containerPort: 8088
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
