#### Hadoop Slave  replication controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: hadoop-slave
  name: hadoop-slave
  namespace: default
spec:
  selector:
    app: hadoop-slave
  template:
    metadata:
      labels:
        app: hadoop-slave
    spec:
      containers:
      - image: tantru/hadoop-slave:1.0
        imagePullPolicy: Always
        name: hadoop-slave
