apiVersion: v1
kind: Service
metadata:
  name: hadoop-slave
  labels:
    app: hadoop-slave
spec:
  ports:
    - port: 50070
      name: hadoop-slave
    - port: 8088
      name: hadoop-slave
  selector:
    app: hadoop-slave
